<?php

namespace ContainerYneugl3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateEmployeeCommand_LazyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateEmployeeCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateEmployeeCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-employee', [], 'Add an employee to the database', false, #[\Closure(name: 'App\\Command\\CreateEmployeeCommand')] fn (): \App\Command\CreateEmployeeCommand => ($container->privates['App\\Command\\CreateEmployeeCommand'] ?? $container->load('getCreateEmployeeCommandService')));
    }
}
