<?php

namespace ContainerYneugl3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCourseEnrollmentServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\CourseEnrollmentService' shared autowired service.
     *
     * @return \App\Services\CourseEnrollmentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/CourseEnrollmentService.php';

        return $container->privates['App\\Services\\CourseEnrollmentService'] = new \App\Services\CourseEnrollmentService(($container->services['messenger.default_bus'] ?? $container->load('getMessenger_DefaultBusService')));
    }
}
