<?php

namespace ContainerYneugl3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateEmployeeCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateEmployeeCommand' shared autowired service.
     *
     * @return \App\Command\CreateEmployeeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateEmployeeCommand.php';

        $container->privates['App\\Command\\CreateEmployeeCommand'] = $instance = new \App\Command\CreateEmployeeCommand(($container->privates['App\\Services\\EmployeeService'] ?? $container->load('getEmployeeServiceService')));

        $instance->setName('app:create-employee');
        $instance->setDescription('Add an employee to the database');

        return $instance;
    }
}
