<?php

namespace ContainerYneugl3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Services\EmployeeService' shared autowired service.
     *
     * @return \App\Services\EmployeeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/EmployeeService.php';

        return $container->privates['App\\Services\\EmployeeService'] = new \App\Services\EmployeeService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['validator'] ?? $container->load('getValidatorService')));
    }
}
