<?php

namespace ContainerYneugl3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPythonCourseEnrollmentHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\MessageHandler\PythonCourseEnrollmentHandler' shared autowired service.
     *
     * @return \App\MessageHandler\PythonCourseEnrollmentHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/MessageHandler/PythonCourseEnrollmentHandler.php';

        return $container->privates['App\\MessageHandler\\PythonCourseEnrollmentHandler'] = new \App\MessageHandler\PythonCourseEnrollmentHandler(($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
