<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYneugl3\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYneugl3/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerYneugl3.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerYneugl3\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerYneugl3\App_KernelTestDebugContainer([
    'container.build_hash' => 'Yneugl3',
    'container.build_id' => '14487167',
    'container.build_time' => 1706533173,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYneugl3');
